PASSAGE_LOCATIONS: list[str] = [
    "Passage-Survivor",
    "Passage-Hunter",
    "Passage-Saint",
    "Passage-Traveller",
    "Passage-Chieftain",
    "Passage-Monk",
    "Passage-Outlaw",
    "Passage-DragonSlayer",
    "Passage-Scholar",
    "Passage-Friend"
]

ECHO_LOCATIONS: list[str] = [
    "Echo-CC",
    "Echo-SI",
    "Echo-LF",
    "Echo-SH",
    "Echo-UW",
    "Echo-SB"
]

PEARL_LOCATIONS: list[str] = [
    "Pearl-SU",
    "Pearl-HI",
    "Pearl-DS",
    "Pearl-CC",
    "Pearl-GW",
    "Pearl-SH",
    "Pearl-SL_bridge",
    "Pearl-SL_chimney",
    "Pearl-SL_moon",
    "Pearl-SI_top",
    "Pearl-SI_west",
    "Pearl-LF_west",
    "Pearl-LF_bottom",
    "Pearl-UW",
    "Pearl-SB_ravine",
    "Pearl-SB_filtration"
]

TOKEN_LOCATIONS: dict[str, list[str]] = {
    "SU": [
        "Token-PoleMimic",
        "Token-CicadaA",
        "Token-DangleFruit",
        "Token-L-SU",
    ],
    "HI": [
        "Token-BlueLizard",
        "Token-SmallCentipede",
        "Token-VultureGrub",
        "Token-FirecrackerPlant",
        "Token-L-HI",
    ],
    "DS": [
        "Token-Leech",
        "Token-Hazer",
        "Token-BubbleGrass",
        "Token-Salamander",
        "Token-Snail",
        "Token-L-DS",
    ],
    "CC": [
        "Token-WhiteLizard",
        "Token-Vulture",
        "Token-CyanLizard",
        "Token-DropBug",
        "Token-L-CC",
    ],
    "GW": [
        "Token-RedLizard",
        "Token-ScavengerBomb",
        "Token-Scavenger",
        "Token-FireSpear",
        "Token-BrotherLongLegs",
        "Token-WaterNut",
        "Token-L-GW",
    ],
    "SH": [
        "Token-BigSpider",
        "Token-Lantern",
        "Token-Spider",
        "Token-LanternMouse",
        "Token-FlareBomb",
        "Token-MirosBird",
        "Token-L-SH",
    ],
    "SL": [
        "Token-SeaLeech",
        "Token-JellyFish",
        "Token-BigEel",
        "Token-JetFish",
        "Token-L-SL",
    ],
    "SI": [
        "Token-KingVulture",
        "Token-Centiwing",
        "Token-EggBug",
        "Token-L-SI",
    ],
    "LF": [
        "Token-BigNeedleWorm",
        "Token-SpitterSpider",
        "Token-Deer",
        "Token-SporePlant",
        "Token-FlyLure",
        "Token-PuffBall",
        "Token-L-LF",
    ],
    "UW": [
        "Token-TubeWorm",
        "Token-YellowLizard",
        "Token-SlimeMold",
        "Token-L-UW",
    ],
    "SS": [
        "Token-DaddyLongLegs",
    ],
    "SB": [
        "Token-BlackLizard",
        "Token-Mushroom",
        "Token-BigCentipede",
        "Token-RedCentipede",
        "Token-TentaclePlant",
        "Token-L-SB",
    ]
}

ALL_LOCATIONS: list[str] = [
    *PASSAGE_LOCATIONS,
    *ECHO_LOCATIONS,
    *PEARL_LOCATIONS,
    *TOKEN_LOCATIONS["SU"],
    *TOKEN_LOCATIONS["HI"],
    *TOKEN_LOCATIONS["DS"],
    *TOKEN_LOCATIONS["CC"],
    *TOKEN_LOCATIONS["GW"],
    *TOKEN_LOCATIONS["SH"],
    *TOKEN_LOCATIONS["SL"],
    *TOKEN_LOCATIONS["SI"],
    *TOKEN_LOCATIONS["LF"],
    *TOKEN_LOCATIONS["UW"],
    *TOKEN_LOCATIONS["SB"],
    "Eat_Neuron",
    "Meet_LttM",
    "Save_LttM",
    "Meet_FP",
]

# ---- Subsets of locations for each slugcat ----
SURVIVOR_LOCATIONS: list[str] = [
    *PASSAGE_LOCATIONS,
    *ECHO_LOCATIONS,
    *PEARL_LOCATIONS,
    *TOKEN_LOCATIONS["SU"],
    *TOKEN_LOCATIONS["HI"],
    *TOKEN_LOCATIONS["DS"],
    "Token-WhiteLizard",
    "Token-Vulture",
    "Token-DropBug",
    "Token-L-CC",
    "Token-ScavengerBomb",
    "Token-Scavenger",
    "Token-FireSpear",
    "Token-BrotherLongLegs",
    "Token-WaterNut",
    "Token-L-GW",
    "Token-BigSpider",
    "Token-Lantern",
    "Token-Spider",
    "Token-LanternMouse",
    "Token-FlareBomb",
    "Token-L-SH",
    "Token-SeaLeech",
    "Token-JellyFish",
    "Token-JetFish",
    "Token-L-SL",
    "Token-Centiwing",
    "Token-EggBug",
    "Token-L-SI",
    "Token-BigNeedleWorm",
    "Token-SporePlant",
    "Token-FlyLure",
    "Token-PuffBall",
    "Token-L-LF",
    *TOKEN_LOCATIONS["UW"],
    *TOKEN_LOCATIONS["SS"],
    "Token-BlackLizard",
    "Token-Mushroom",
    "Token-BigCentipede",
    "Token-L-SB",
    "Eat_Neuron",
    "Meet_LttM",
    "Meet_FP"
]

MONK_LOCATIONS: list[str] = [
    *PASSAGE_LOCATIONS,
    *ECHO_LOCATIONS,
    *TOKEN_LOCATIONS["SU"],
    *TOKEN_LOCATIONS["HI"],
    "Token-Leech",
    "Token-Hazer",
    "Token-Salamander",
    "Token-Snail",
    "Token-L-DS",
    "Token-WhiteLizard",
    "Token-Vulture",
    "Token-L-CC",
    "Token-ScavengerBomb",
    "Token-Scavenger",
    "Token-FireSpear",
    "Token-BrotherLongLegs",
    "Token-WaterNut",
    "Token-L-GW",
    "Token-BigSpider",
    "Token-Lantern",
    "Token-Spider",
    "Token-LanternMouse",
    "Token-FlareBomb",
    "Token-L-SH",
    "Token-JellyFish",
    "Token-JetFish",
    "Token-L-SL",
    "Token-EggBug",
    "Token-L-SI",
    "Token-BigNeedleWorm",
    "Token-SporePlant",
    "Token-FlyLure",
    "Token-PuffBall",
    "Token-L-LF",
    "Token-TubeWorm",
    "Token-YellowLizard",
    "Token-L-UW",
    *TOKEN_LOCATIONS["SS"],
    "Token-BlackLizard",
    "Token-Mushroom",
    "Token-BigCentipede",
    "Token-L-SB",
    "Eat_Neuron",
    "Meet_LttM",
    "Meet_FP"
]

HUNTER_LOCATIONS: list[str] = [
    *PASSAGE_LOCATIONS,
    *ECHO_LOCATIONS,
    *PEARL_LOCATIONS,
    *TOKEN_LOCATIONS["SU"],
    *TOKEN_LOCATIONS["HI"],
    *TOKEN_LOCATIONS["DS"],
    *TOKEN_LOCATIONS["CC"],
    *TOKEN_LOCATIONS["GW"],
    *TOKEN_LOCATIONS["SH"],
    *TOKEN_LOCATIONS["SL"],
    *TOKEN_LOCATIONS["SI"],
    *TOKEN_LOCATIONS["LF"],
    *TOKEN_LOCATIONS["UW"],
    "Token-BlackLizard",
    "Token-Mushroom",
    "Token-BigCentipede",
    "Token-RedCentipede",
    "Token-TentaclePlant",
    "Token-L-SB",
    "Eat_Neuron",
    "Save_LttM",
    "Meet_FP",
]

GATE_ITEMS: list[str] = [
    "GATE_SU_HI",
    "GATE_SU_DS",
    "GATE_HI_GW",
    "GATE_HI_SH",
    "GATE_HI_CC",
    "GATE_DS_SB",
    "GATE_DS_GW",
    "GATE_GW_SL",
    "GATE_SH_UW",
    "GATE_SH_SL",
    "GATE_UW_SS",
    "GATE_SS_UW",
    "GATE_CC_UW",
    "GATE_SI_LF",
    "GATE_SI_CC",
    "GATE_LF_SB",
    "GATE_LF_SU",
    "GATE_SB_SL",
]

PASSAGE_ITEMS: list[str] = [
    "Passage-Survivor",
    "Passage-Hunter",
    "Passage-Saint",
    "Passage-Traveller",
    "Passage-Chieftain",
    "Passage-Monk",
    "Passage-Outlaw",
    "Passage-DragonSlayer",
    "Passage-Scholar",
    "Passage-Friend"
]

ALL_ITEMS: list[str] = [
    *GATE_ITEMS,
    *PASSAGE_ITEMS,
    "Karma",
    "The Glow",
    "The Mark"
]